### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by ghost** [JacobMisirian/Hassium-Rewrite#1]
There appear to be several problems with operator precedence in Hassium. The operator precedence in Hassium is roughly

Assignment (5)
Additive (4)
Multiplicative/bitwise??? (3)
Unary (2)
Boolean (1)
Member access (0)

Please see http://en.cppreference.com/w/c/language/operator_precedence
The following examples demonstrate the problems with operator precedence 

`4 ^ 2 * 2` This _should_ equal 0, it does not in Hassium
`2 + 2 == 4` This _should_ equal True, it does not in Hassium (Exception is raised)
`7 ^ 3 & 9` This _should_ equal 6, won't compile in Hassium
`7 + 3 & 3 - 2 ^ 5 * 2` This _should_ equal 10, won't compile in Hassium

**Comment by JacobMisirian** [comment]
The latest commit now fixes these.
