### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ghost** [JacobMisirian/Hassium-Rewrite#2]
I have discovered a very serious memory leak in Hassium. The following program will continuously use more and more memory.

```
func foo (i) {
    return i;
}

func main () {
    i = 0;
    while (true) {
        println (foo (i));
        i = i + 1;
    }
}
```

**Comment by JacobMisirian** [comment]
The latest commit fixes this issue. For me the RAM usage hovered at around 1.2%
